apiVersion: apps/v1
kind: Deployment
metadata:
  name: catfacts-generator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catfacts-generator
  template:
    metadata:
      labels:
        app: catfacts-generator
    spec:
      containers:
        - name: catfacts-generator
          image: kacgod/catfacts-generator
          ports:
            - containerPort: 80
