apiVersion: v1
kind: Service
metadata:
  name: catfacts-generator-service
spec:
  selector:
    app: catfacts-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer